# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.file_uploader:
        class: TikaBundle\FileUploader
        arguments: ['%uploadedfiles%']

    app.meta_file_reader:
        class: TikaBundle\MetaFileReader
        arguments: [filePath]