<?php

namespace TikaBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpFileRepository extends \Doctrine\ORM\EntityRepository
{
}
